INSERT INTO USER_ENTITY_TABLE(ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(1,'abc@gmail.com','Abc Xyz', '989878787', 'abc123');

INSERT INTO USER_ENTITY_TABLE(ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(2,'xyz@gmail.com','Xyz Pqr', '8976877668', 'xyz123');
